# Generated by Django 2.1.7 on 2019-02-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20190226_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='mobile',
            field=models.BigIntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='mobile',
            field=models.BigIntegerField(max_length=100),
        ),
    ]
